project:
  type: website
  output-dir: docs

execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Generalized Linear Models"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - slides.qmd
      - labs.qmd
    right:
      - icon: github
        href: https://github.com/stat-teaching/GLMphd
        aria-label: GitHub

institute: "University of Padova"
author:
  - name: "Filippo Gambarota"
    email: filippo.gambarota@unipd.it
    twitter: fgambarota
    github: filippogambarota

format:
  html:
    theme: brite
    toc: true



