---
title: "Generalized Linear Models"
subtitle: "PhD Program in Psychological Sciences - University of Padova"
---

```{r, include=FALSE}
devtools::load_all()
library(kableExtra)
```

# Course

This repository contains the materials for the course *Generalized Linear Models* from the PhD program in Psychological Sciences (University of Padova). The repository is organized as an R Package.

## Getting Started

To start with the course you can download or clone the entire Git repository. Simply run `git clone link` or follow this link.

Then you can open the `GLMphd.Rproj` file and R Studio will be opened on the correct folder. From now, everything is organized as a package. To load all the custom function of the `R` folder and datasets (`data` folder) you can use `devtools::load_all()`. This is the same as doing `source("file.R")` without cluttering the global environment.

# Schedule

|     Day    |     Hour    | Room |    Course    |
|:----------:|:-----------:|:----:|:------------:|
| 20-11-2023 | 09:00-12:00 |  4T  | GLM - Part A |
| 21-11-2023 | 09:00-11:00 |  4T  | GLM - Part A |
| 27-11-2023 | 14:30-17:30 |  4M  | GLM - Part A |
| 28-11-2023 | 14:30-16:30 |  4N  | GLM - Part A |
| 04-12-2023 | 09:00-12:00 |  4T  | GLM - Part B |
| 05-12-2023 | 09:00-11:00 |  4T  | GLM - Part B |

